### ISSUE TITLE
Views must be protected

### ISSUE THREAD

**Issue by tkwon** [skbhagat40/To-Do-List#11]
Currently I have a task created at this URL:

http://todolist40.herokuapp.com/9/

If I log out and try to view the url as an anonymous user, I can see the task. So the view is not "protected". We must use decorators (FBV) or mixin (CBV) to protect views.

1) We can use django-braces of the builtin "loginrequired" decorator to make sure someone is authenticated.

2) we must check if authenticated user is owner of the task before displaying it.
This may require adding the author/owner to each task model.

**Comment by skbhagat40** [comment]
I think it sorted now. But I am not completely sure.
